import type { Lang } from "./lang";

// Zentrale Copy-/Daten-Quelle fuer die gesamte Website, zweisprachig (DE/EN).
// Icons sind sprachunabhaengig und leben in _icons.tsx, hier nur Text/Zahlen.
// Beide Sprachversionen muessen exakt dieselbe Form haben (type Dictionary =
// typeof de erzwingt das fuer en) -- gleiches Prinzip wie lib/i18n/dict.ts in
// der Haupt-App.

const de = {
  nav: {
    produkt: "Produkt",
    produktItems: [
      { label: "Workflow", href: "#produkt" },
      { label: "Personalisierung", href: "#personalisierung" },
      { label: "Integrationen", href: "#integrationen" },
    ],
    agenturen: "Für Agenturen",
    preise: "Preise",
    vergleich: "Vergleich",
    faq: "FAQ",
    kontakt: "Kontakt",
  },
  trustBar: {
    heading: "Läuft mit etablierten Diensten im Hintergrund",
    partners: ["OpenAI", "Google Places", "Hunter.io", "NeverBounce", "Instantly"],
  },
  heroIllustration: {
    badgeStat: "2×",
    badgeLabel: "mehr Antworten durch echte Personalisierung",
    inboxLabel: "Antworten, live aus dem Dashboard",
    replies: [
      { name: "Markus Huber", company: "Schreinerei Huber", message: "Klingt gut, erzählt mir mehr!", status: "reply" },
      { name: "Julia Berger", company: "Zahnarztpraxis Berger", message: "Ja, gerne! Passt euch Dienstag 14 Uhr?", status: "meeting" },
      { name: "Elena Roth", company: "Café Sonnenblick", message: "Interessant, wann könnt ihr kurz telefonieren?", status: "reply" },
    ],
    replyLabel: "Antwort",
    meetingLabel: "Meeting gebucht",
  },
  calculator: {
    eyebrow: "Interaktiv",
    title: "Berechne dein Sparpotenzial",
    subtitle: "Wie viele qualifizierte Leads willst du pro Monat erreichen? Wir rechnen live vor, was das für dich bedeutet.",
    sliderLabel: "Qualifizierte Leads / Monat",
    hoursUnit: "Std.",
    hoursLabel: "manuelle Recherche gespart / Monat",
    laborLabel: "Arbeitszeit-Gegenwert dafür",
    meetingsLabel: "Meetings / Monat rechnerisch",
    planPrefix: "Dafür passt der",
    apiCostPrefix: "ca.",
  },
  cta: {
    primary: "Kostenlos testen",
    secondary: "Oder Call buchen",
    trialNote: "14 Tage kostenlos, keine Kreditkarte nötig. Monatlich kündbar, keine Vertragslaufzeit.",
  },
  hero: {
    eyebrow: "Der wohl direkteste KI-Einsatz für Kaltakquise",
    h1Pre: "Mindestens ",
    h1Accent: "5.000 echte Ansprechpartner",
    h1Post: " pro Woche anschreiben, vollautomatisch.",
    body: "Frostbreaker findet lokale Unternehmen, identifiziert die richtige Person dahinter, verifiziert die E-Mail-Adresse und schreibt eine individuelle Icebreaker-Zeile, vollautomatisch. Kein info@, kein office@: nur echte Menschen, die man wirklich erreichen kann.",
    factBadge: "Agenturen bekommen im Schnitt 42 € zurück für jeden Euro, den sie in E-Mails stecken.",
    factSource: "Quelle: Litmus, State of Email 2025",
    screenshotAlt: "Frostbreaker Leads-Tabelle mit Firmen-Logos, Kontaktanzahl und E-Mail-Status",
  },
  heroStats: [
    { value: "≈ 133 Std.", label: "manuelle Recherche gespart, pro 1.000 Leads" },
    { value: "65 €", label: "tatsächliche API-Kosten dafür" },
    { value: "1 Tool", label: "statt vier einzelne Abos" },
  ],
  leadSource: {
    eyebrow: "Die Lead-Quelle macht den Unterschied",
    title: "Findet die kleinen, lokalen Unternehmen, die in klassischen Lead-Datenbanken kaum auftauchen",
    body1: "Klassische B2B-Datenbanken bauen auf LinkedIn-Profilen und strukturierten Firmendaten auf, das bevorzugt Unternehmen mit digitaler Präsenz: Software-Firmen, größere Mittelständler, Agenturen selbst. Der Handwerksbetrieb, das Nachbarschaftsrestaurant, die Zahnarztpraxis, die kleine Kanzlei, oft genau die Betriebe, die Marketing am dringendsten bräuchten, weil sie selbst noch nie strukturiert investiert haben, tauchen dort kaum auf.",
    body2: "Frostbreaker sucht stattdessen direkt über Google Places/Google Maps, wo praktisch jedes Unternehmen mit physischer Adresse gelistet ist, unabhängig von digitaler Reife. Für eine Agentur heißt das: Zugriff auf genau die lokalen Kund:innen, die sonst zwischen den Zähnen der üblichen Prospecting-Tools durchfallen.",
  },
  localReachMockup: {
    typicalLabel: "Typische B2B-Datenbank",
    frostbreakerLabel: "Frostbreaker, über Google Places",
    notListed: "nicht gelistet",
    businesses: [
      { name: "Frisör Kaiser", sub: "Einzelsalon, 1 Standort" },
      { name: "Schreinerei Huber", sub: "Handwerksbetrieb, 6 Mitarbeitende" },
      { name: "Zahnarztpraxis Dr. Berger", sub: "Einzelpraxis" },
    ],
  },
  qualifiedLeads: {
    eyebrow: "Echte Menschen, keine info@-Adressen",
    title: "Jeder Lead ist eine Person, die man wirklich erreichen kann",
    body1: "Die meisten Tools liefern, was sie finden, inklusive info@, office@ und kontakt@-Adressen, an denen niemand konkret zuständig ist. Frostbreaker filtert das automatisch heraus: nur Adressen, die eindeutig einer echten Person zugeordnet sind, kommen überhaupt in eure Leads-Liste.",
    body2: "Kein Reply-to-nowhere. Kein Antworten ins Leere. Nur echte Ansprechpartner.",
  },
  qualifiedMockup: {
    typicalLabel: "Typisches Tool",
    frostbreakerLabel: "Frostbreaker",
    genericNote: "Rollen-Adresse, niemand konkret zuständig",
    rows: [
      { generic: "info@schreinerei-huber.de", name: "Markus Huber", role: "Inhaber", email: "m.huber@schreinerei-huber.de" },
      { generic: "office@zahnarzt-berger.at", name: "Dr. Anna Berger", role: "Praxisinhaberin", email: "a.berger@zahnarzt-berger.at" },
      { generic: "kontakt@frisoer-kaiser.de", name: "Julia Kaiser", role: "Salonleitung", email: "j.kaiser@frisoer-kaiser.de" },
    ],
  },
  painPoints: {
    title: "Kommt dir bekannt vor?",
    subtitle: "Jede Stunde manuelle Recherche ist eine Stunde, die weder abgerechnet noch für neue Kund:innen genutzt wird, und multipliziert sich mit jedem zusätzlichen Kunden-Account.",
    items: [
      { title: "Für jeden Kunden ein eigenes Tool-Chaos", body: "Ein Login für die Recherche, eins für den Versand, eine Tabelle fürs Reporting, pro Kunde von vorne. Am Monatsende wird der Report von Hand zusammengeschustert." },
      { title: "Stunden im Research versenkt", body: "Google, LinkedIn, Impressum-Suche, E-Mail raten: Bevor die erste Mail für einen Kunden überhaupt raus ist, ist schon der halbe Tag weg." },
      { title: "Vier Abos für einen Workflow", body: "Ein Tool für Kontakte, eins für Verifizierung, eins für Personalisierung, eins für den Versand, dazwischen CSV-Dateien von Hand exportiert, für jeden Kunden erneut." },
      { title: "Bounce-Raten, die die Domain ruinieren", body: "Ungeprüfte Adressen killen die Zustellrate. Bei mehreren Kunden-Domains gleichzeitig merkt man's oft erst, wenn bei einem Kunden die Antwortquote plötzlich einbricht." },
      { title: "Generische Mails, die jeder erkennt", body: "„Hi {{Firstname}}, ich hab gesehen dass {{Company}}...“ mit Textbaustein-Personalisierung performt schlechter als gar keine, und schadet der eigenen Kundenbindung." },
      { title: "Info@ statt echtem Ansprechpartner", body: "Die Hälfte der „gefundenen“ Adressen landet in einem geteilten Postfach, das niemand konsequent liest. Cold Mail an info@ ist kaum besser als gar keine Mail." },
    ],
  },
  pillars: {
    eyebrow: "Der Effekt in vier Sätzen",
    title: "Was sich für euch konkret ändert",
    items: [
      { id: "money", title: "Geld sparen", stat: "≈ 285 €", statLabel: "gespart pro Monat ggü. einem vergleichbaren 4-Tool-Stack", body: "Ihr zahlt nur eure echten API-Kosten, ≈ 65 € für 1.000 Leads, plus den Plan, keine Aufschläge. Ein vergleichbarer Stack aus Datenquelle, Versand-Tool und Automatisierung (z. B. Apollo/Clay + Instantly + Zapier) kostet meist 250–650 €/Monat." },
      { id: "revenue", title: "Umsatz steigern", stat: "≈ 6", statLabel: "Meetings/Monat rechnerisch, bei 1.000 versendeten Mails", body: "Echte Personalisierung statt Textbausteine, jede Mail erreicht eine echte Person statt eine Rollen-Adresse." },
      { id: "time", title: "Zeit sparen", stat: "≈ 133 Std.", statLabel: "manuelle Recherche gespart, pro 1.000 Leads", body: "Keine manuelle Suche, kein Adressraten, kein CSV-Jonglieren zwischen mehreren Tools." },
      { id: "risk", title: "Risiko sparen", stat: "3-fach", statLabel: "Verifizierung, Zustellbarkeits-Check und Blockliste eingebaut", body: "Schützt Sender-Reputation und Domain, bevor es zum Problem wird, nicht danach. EU-Hosting, verschlüsselte Zugangsdaten." },
    ],
  },
  workflow: {
    title: "Ein Workflow. Vier Schritte. Vollautomatisch, auf Knopfdruck.",
    subtitle: "Einmal Nische und Kriterien festlegen, den Rest übernimmt Frostbreaker: kein manueller Zwischenschritt, kein Warten auf einen Praktikanten, keine Excel-Liste von Hand.",
    steps: [
      { n: "1", title: "Suchen", body: "Nische und Ort eingeben, Frostbreaker findet automatisch passende Unternehmen, für jeden Kunden im eigenen Workspace." },
      { n: "2", title: "Finden", body: "Entscheider:innen mit Namen werden automatisch ermittelt, keine info@- oder office@-Treffer." },
      { n: "3", title: "Verifizieren", body: "Jede Adresse wird geprüft, bevor sie in eine Kampagne geht. Zusätzlich prüft Frostbreaker SPF, DKIM und DMARC eurer Sende-Domain, bevor überhaupt eine Kampagne live geht." },
      { n: "4", title: "Personalisieren & Versenden", body: "Eine KI schreibt pro Lead eine individuelle Icebreaker-Zeile. Sequenz, Zeitplan und Aktivierung laufen danach direkt in Frostbreaker, kein Tool-Wechsel mehr nötig." },
    ],
    fact: { fact: "Kleine, gezielte Listen bekommen fast dreimal mehr Antworten als riesige Listen.", sub: "Lieber wenige, gut ausgewählte Unternehmen anschreiben als tausende wahllos.", source: "Woodpecker, mit Verweis auf Belkins-Analyse von 16,5 Mio. E-Mails, 2026" },
  },
  agency: {
    eyebrow: "Für Agenturen",
    title: "Mehrere Kunden verwalten, ohne für jeden ein neues Abo aufzumachen",
    body: "Betreut ihr Lead-Gen oder Cold Outreach für eure eigenen Kunden? Dann läuft jeder Kunde in einem eigenen, sauber getrennten Workspace, im Look dieses Kunden, unter einem einzigen Login für euer Team.",
    features: [
      { id: "workspaces", title: "Ein Login, ein Workspace pro Kunde", body: "Leads, Kampagnen und Kontakte laufen pro Kunde sauber getrennt, ohne für jeden ein eigenes Abo abzuschließen. Workspaces lassen sich in Sekunden anlegen, umbenennen oder wieder entfernen." },
      { id: "branding", title: "Branding pro Kunden-Workspace", body: "Name, Logo und Akzentfarbe lassen sich je Workspace hinterlegen, damit das, was der Endkunde sieht, nach der Agentur aussieht, nicht nach einem fremden Tool im Hintergrund." },
      { id: "reportLink", title: "Teilbarer Report-Link, ohne Login für den Endkunden", body: "Ein Link pro Workspace zeigt aggregierte Kennzahlen im Look des jeweiligen Kunden, ganz ohne dass der einen eigenen Account braucht. Einzelne Kontaktdaten sieht der Endkunde dabei bewusst nicht." },
    ],
    note: "Bei reinen Versand-Tools ist eine Multi-Kunden-Verwaltung meist ein separat bepreistes Zusatzmodul, oft mit einem eigenen Preis pro angelegtem Kunden-Workspace, obendrauf auf ein Tool, das nur den Versand übernimmt. Bei Frostbreaker ist das von Anfang an Teil des Produkts.",
  },
  agencyMockup: {
    workspacesLabel: "Workspaces",
    active: "aktiv",
    workspaces: [
      { name: "Kunde: Muster GmbH", color: "#0EA5E9", active: true },
      { name: "Kunde: Beispiel AG", color: "#8B5CF6", active: false },
      { name: "Kunde: Nordwind KG", color: "#F59E0B", active: false },
    ],
    brandingLabel: "Branding dieses Workspaces",
    brandingValue: "Muster GmbH · Akzentfarbe #0EA5E9",
    reportLinkLabel: "Report-Link für den Endkunden",
    copyLabel: "Kopieren",
  },
  postSend: {
    eyebrow: "Mehr als Lead-Suche",
    title: "Die meisten Tools hören auf, sobald die Mail raus ist. Frostbreaker nicht.",
    body: "Über eine Verbindung zu eurem Versandtool fließen Antworten, Bounces und Meeting-Ergebnisse zurück in dasselbe Dashboard, in dem die Leads gefunden wurden.",
    features: [
      { id: "replies", title: "Antworten lesen und direkt beantworten", body: "Jede eingehende Antwort landet mit vollem Text in Frostbreaker, KI ordnet sie sofort ein (interessiert, kein Interesse, Rückfrage). Direkt aus der App heraus antworten, kein Wechsel zu einem separaten Tool." },
      { id: "dashboard", title: "Umsatzbezogenes Dashboard statt nur Öffnungsrate", body: "Gebuchte Meetings, geschätzter Pipeline-Wert und Kosten pro Opportunity, direkt im selben Dashboard wie die Lead-Suche." },
      { id: "status", title: "Lead-Status pro Kontakt, ohne separates CRM", body: "Kontaktiert, geantwortet, Meeting gebucht, Kunde geworden, alles direkt in der Leads-Tabelle nachvollziehbar." },
      { id: "deliverability", title: "SPF, DKIM, DMARC: geprüft, bevor ihr sendet", body: "Frostbreaker prüft eure Sende-Domain live per DNS-Abfrage und zeigt in Klartext, was zu tun ist, kein separates Tool nötig. Dazu Tagesvolumen pro Postfach auf einen Blick, mit Warnung bei riskant hohem Sendevolumen." },
    ],
  },
  postSendMockup: {
    incomingLabel: "Eingehende Antwort, automatisch eingeordnet",
    exampleReply: "„Klingt interessant, können wir nächste Woche kurz telefonieren?“",
    statusInterested: "Interessiert",
    dashboardLabel: "Fiktives Beispiel-Dashboard",
    meetings: "Meetings gebucht",
    pipeline: "Pipeline-Wert",
    bounce: "Bounce-Rate",
  },
  personalization: {
    eyebrow: "Personalisierung",
    title: "Der KI-Agent ist keine Blackbox",
    body: "Die meisten Tools spucken einen Icebreaker aus, ohne dass ihr wisst, worauf er sich stützt oder wie er klingt. Bei Frostbreaker stellt ihr das selbst ein: pro Nische, pro Kampagne, so oft ihr wollt.",
    bullets: [
      { label: "Datenquelle wählen:", body: "Firmenbeschreibung, Website-Text oder beides kombiniert." },
      { label: "System-Prompt vollständig editierbar:", body: "ihr bestimmt Ton, Regeln und Struktur, kein starres Template." },
      { label: "Verbotene Wörter definieren:", body: "damit kein Icebreaker nach generischer KI klingt." },
      { label: "Live-Test an einer echten, recherchierten Firma:", body: "bevor irgendetwas gespeichert oder verschickt wird." },
    ],
    dataSourceLabel: "Datenquelle",
    sourceOptions: ["Firmenbeschreibung", "Website-Text", "Beides kombiniert"],
    promptLabel: "System-Prompt",
    promptLines: [
      "- Nutze ausschließlich überprüfbare Fakten aus der Recherche.",
      "- Kein Name, keine Begrüßung, keine Floskeln.",
      "- Direkt, konkret, wie eine Beobachtung vor einer Vertriebsfrage.",
    ],
    forbiddenLabel: "Verbotene Wörter",
    forbiddenWords: ["Respekt", "bewundern", "stolz", "Lob", "begeistert"],
  },
  integrations: {
    eyebrow: "Passt in euren Stack",
    title: "Exportiert direkt in die Tools, die ihr schon nutzt",
    items: [
      { name: "Instantly", note: "Vollständig natives Kampagnen-Management, kein CSV-Export nötig" },
      { name: "Smartlead", note: "CSV-Import" },
      { name: "Lemlist", note: "CSV-Import" },
      { name: "HubSpot", note: "CSV-Import" },
      { name: "Pipedrive", note: "CSV-Import" },
      { name: "Salesforce", note: "CSV-Import" },
      { name: "Excel / Sheets", note: "Excel-CSV" },
      { name: "Zapier", note: "geplant" },
    ],
  },
  usps: {
    eyebrow: "Warum Frostbreaker",
    title: "Warum Frostbreaker und nicht vier einzelne Tools",
    items: [
      { title: "Alles in einem Tool, pro Kunde getrennt", body: "Suche, Anreicherung, Verifizierung, Personalisierung und Export laufen in einem einzigen Workflow, je Kunden-Workspace sauber getrennt. Kein CSV-Hin-und-Her zwischen vier Abos mehr." },
      { title: "Individuelle KI-Zusammenfassung pro Lead", body: "Für jedes Unternehmen wird automatisch eine faktenbasierte Zusammenfassung erstellt, Grundlage für einen Icebreaker, der wirklich nach Recherche klingt. Ton, Regeln und verbotene Wörter sind vollständig einstellbar.", fact: "Persönliche E-Mails bekommen etwa doppelt so oft eine Antwort wie 08/15-Mails.", sub: "Fast niemand macht das von Hand, weil es zu lange dauert. Frostbreaker übernimmt das für euch, bei jeder einzelnen E-Mail.", source: "Woodpecker, Auswertung von über 20 Mio. E-Mails, 2026" },
      { title: "E-Mail-Verifizierung eingebaut", body: "Jede gefundene Adresse wird geprüft, bevor sie in eine Kampagne geht. Das schützt eure Sender-Reputation, ohne ein zusätzliches Tool.", fact: "Geprüfte E-Mail-Adressen kommen etwa doppelt so oft an wie ungeprüfte.", sub: "Zu viele falsche Adressen und eure Mails landen im Spam statt im Postfach.", source: "Branchen-Benchmarks E-Mail-Zustellbarkeit, 2026" },
      { title: "Bring Your Own Key: volle Kostentransparenz", body: "Ihr zahlt die tatsächlichen API-Kosten, keine versteckten Aufschläge. Im Dashboard seht ihr live, was eine Suche tatsächlich gekostet hat." },
      { title: "DSGVO-bewusst gebaut", body: "EU-Hosting, verschlüsselte Speicherung von Zugangsdaten, Datensparsamkeit von Grund auf mitgedacht." },
      { title: "Direkter Draht zum Team", body: "Kein Ticket-System. Ihr sprecht direkt mit den Leuten, die das Tool gebaut haben, inklusive echter Anpassungen auf Wunsch." },
      { title: "Filtert nach echten Pain Points, nicht nur nach Branche und Ort", body: "Google-Bewertung und ob überhaupt eine Website existiert fließen direkt in die Suche ein. Der Icebreaker bezieht dieses Signal automatisch mit ein, zum Beispiel wenn ein Unternehmen seit Jahren keine aktuelle Bewertung oder gar keine Website hat, statt nur Firmenname und Branche zu kennen." },
      { title: "Fertige Branchen-Playbooks statt eigenem Trial-and-Error", body: "Vorgefertigte Kombinationen aus Suchkriterien, Pain-Point-Filter und Personalisierungs-Hinweis für gängige Nischen, etwa Restaurants ohne aktuelle Website oder Handwerksbetriebe ohne Terminbuchung. Ein Klick statt tagelangem Herumprobieren mit Suchbegriffen." },
    ],
  },
  trustBadges: [
    { id: "euHosting", title: "EU-Hosting", body: "Server in Frankfurt, keine Datenübertragung außerhalb der EU." },
    { id: "encryption", title: "Verschlüsselte API-Keys", body: "Eure Zugangsdaten werden verschlüsselt gespeichert, nie im Klartext." },
    { id: "byok", title: "BYOK-Kostenkontrolle", body: "Volle Transparenz über eure tatsächlichen API-Kosten, live im Dashboard." },
  ],
  proofStat: {
    label: "Kein Testimonial, echte Zahl aus dem eigenen Account",
    body: "≈ 33 Stunden manuelle Recherche gespart, rund 1.500 € Arbeitskosten, bei $2,75 tatsächlichen API-Kosten.",
    sub: "So sieht das für eine einzelne Suche im eigenen Dashboard aus: live, nicht nachgerechnet.",
  },
  scaling: {
    eyebrow: "Skalierungspotenzial",
    title: "Was rechnerisch möglich ist, wenn ihr Vollgas gebt",
    tiles: [
      { value: "125.000", label: "personalisierte E-Mails pro Monat versendbar" },
      { value: "bis 125.000", label: "erreichbare Unternehmen pro Monat" },
      { value: "≈ 16.700 Std.", label: "manuelle Recherche gespart, rund 100 Vollzeitstellen/Monat" },
      { value: "≈ 780", label: "qualifizierte Meetings pro Monat rechnerisch möglich" },
    ],
    methodologyLabel: "So kommen die Zahlen zustande, keine Garantie:",
    methodologyBody: "Wir rechnen mit 125.000 verschickten E-Mails im Monat (möglich wären sogar bis zu 500.000). Neue Unternehmen zu finden ist praktisch unbegrenzt, der Versand ist der eigentliche Engpass. Für die Zeitersparnis rechnen wir mit rund 8 Minuten Handarbeit pro Kontakt, für die Kostenersparnis mit 45 € Stundenlohn. Für die Meetings rechnen wir mit 5% Antwortquote, davon ein Viertel positiv, davon die Hälfte führt zu einem Termin, branchenübliche Werte, keine Garantie. Fast die Hälfte aller Antworten kommt übrigens erst von der zweiten Mail, nicht von der ersten, deshalb zählt ein sauberer Export in euer Versandtool mit dazu. Euer echtes Ergebnis hängt von eurer Nische und eurem Angebot ab.",
    agencyOnlyNote: "Diese Zahlen zeigen das Potenzial bei unlimitierten Leads, verfügbar ab dem Agentur-Plan. Auf Starter (bis 5.000 qualifizierte Leads/Monat) skalieren sie entsprechend kleiner:",
    starterTiles: [
      { value: "≈ 133 Std.", label: "Recherchezeit gespart / Monat" },
      { value: "≈ 6.000 €", label: "Arbeitszeit-Gegenwert dafür" },
      { value: "≈ 204 €", label: "Gesamtkosten (Frostbreaker + Versand + APIs)" },
    ],
  },
  pricing: {
    eyebrow: "Preise",
    title: "Feste Preise, sofort einsehbar, kurzes Kennenlerngespräch inklusive",
    agencyBadge: "Für Agenturen",
    note: "14 Tage kostenlos testen, keine Kreditkarte nötig. Danach monatlich kündbar, keine Mindestlaufzeit. Zusätzlich nur eure eigenen API-Kosten, live im Dashboard einsehbar.",
    plans: [
      {
        id: "starter",
        label: "Starter",
        price: "99 €",
        priceNote: "/ Monat",
        features: [
          "1 Workspace",
          "Bis 5.000 qualifizierte Leads/Monat",
          "Nur personenbezogene E-Mails, kein info@",
          "Native Instantly-Kampagnen",
          "Zustellbarkeits-Check & Antwortverwaltung",
        ],
        ctaLabel: "Kostenlos testen",
        highlighted: false,
      },
      {
        id: "agency",
        label: "Agentur",
        price: "ab 199 €",
        priceNote: "/ Monat",
        features: [
          "Mehrere Workspaces, 1 pro Kunde",
          "Unlimitierte qualifizierte Leads",
          "Alles aus Starter",
          "Whitelabel-Reports mit eigenem Branding",
          "Priority Support",
        ],
        ctaLabel: "Preise besprechen",
        highlighted: true,
      },
    ],
  },
  comparison: {
    title: "Im Vergleich",
    headerFrostbreaker: "Frostbreaker",
    headerOther: "Typischer Alternativ-Stack einer Agentur",
    rows: [
      ["Lokale Kleinunternehmen finden", "Ja, direkt über Google Places/Maps", "Meist nicht gelistet, da kein LinkedIn-Profil oder strukturierte Firmendaten"],
      ["Alles in einem Workflow", "Ja", "Nein, separates Recherche-Tool + Sende-Tool + eigenes Reporting"],
      ["Mehrere Kunden verwalten", "Eigener Workspace pro Kunde inklusive", "Meist ein separat bepreistes White-Label-Add-on"],
      ["Reporting für den Endkunden", "Teilbarer Report-Link im Look des Kunden", "Von Hand aus mehreren Tools zusammengebaut"],
      ["KI-Personalisierung pro Lead", "Ja, mit einstellbaren Regeln", "Teilweise, oft separates Tool nötig"],
      ["E-Mail-Verifizierung eingebaut", "Ja", "Separates Tool nötig"],
      ["EU-Hosting", "Ja", "Unterschiedlich, meist US-Anbieter"],
      ["Nur echte Ansprechpartner, kein info@", "Automatisch gefiltert", "Meist ungefiltert"],
      ["Preistransparenz", "Feste Preise, 14 Tage kostenlos testen", "Meist individuelles Angebot, keine Testphase"],
      ["Support", "Direkter Draht zum Gründerteam", "Ticket-System"],
    ] as [string, string, string][],
  },
  trust: {
    title: "Datenschutz ist keine Checkbox, sondern Teil der Architektur",
    links: { datenschutz: "Datenschutzerklärung", agb: "AGB", avv: "AVV" },
  },
  why: {
    title: "Warum es Frostbreaker gibt",
    body: "Outbound-Teams kombinieren heute meist vier bis fünf einzelne Tools, um vom ersten Suchbegriff bis zur personalisierten, verifizierten E-Mail zu kommen. Frostbreaker reduziert diesen Workflow auf ein einziges Tool, mit voller Kostentransparenz statt Pauschal-Abos und ohne CSV-Hin-und-Her zwischen Anbietern.",
    earlyAccess: { title: "Früher Zugang statt großer Kundenliste", body: "Frostbreaker ist aktuell in aktiver Erprobung mit den ersten Partneragenturen. Bewusst eine kleine, eng begleitete Gruppe statt eines anonymen Massenprodukts, jede Anpassung geht direkt in den nächsten Sprint." },
    founderLabel: "Vom Gründer",
    founderQuote: "„Ich wollte schon immer etwas Eigenes aufbauen. Das größte Hindernis war nie die Idee, sondern Kunden zu finden: Kaltakquise per Hand, endlose Anrufe und E-Mails, ohne je zu wissen, ob es sich lohnt. Also habe ich mir selbst das Werkzeug gebaut, das mir gefehlt hat, seitdem geht mir der nächste Ansprechpartner nie mehr aus.“",
    founderName: "Youssef Tayachi",
    founderRole: "Gründer & CEO, Frostbreaker",
    poweredBy: { title: "Läuft mit etablierten Diensten", body: "Keine Blackbox, sondern bekannte, geprüfte Anbieter im Hintergrund." },
  },
  faq: {
    title: "Häufige Fragen",
    items: [
      { q: "Ist das DSGVO-konform?", a: "Die App selbst ist datenschutzbewusst gebaut (EU-Hosting, Verschlüsselung, Datensparsamkeit). Wie ihr die gefundenen Kontakte anschreibt, unterliegt weiterhin den für euch geltenden Regeln zur Direktwerbung. Dazu beraten wir euch im Gespräch gerne konkret für eure Situation." },
      { q: "Kann ich das als Agentur für mehrere Kunden gleichzeitig nutzen?", a: "Ja, dafür gibt es eigene Workspaces pro Kunde, inklusive eigenem Namen, Logo und Akzentfarbe. Für jeden Workspace lässt sich ein Report-Link teilen, der eurem Endkunden aggregierte Kennzahlen im eigenen Look zeigt, ganz ohne dass der einen eigenen Account braucht." },
      { q: "Was kostet das?", a: "99 € im Monat für den Starter-Plan (1 Workspace, bis 5.000 qualifizierte Leads), 14 Tage kostenlos testen, danach monatlich kündbar. Der Agentur-Plan (mehrere Workspaces, unlimitiert) startet ab 199 € im Monat, abgestimmt auf eure Anzahl an Kunden-Workspaces, dafür sprechen wir kurz miteinander. Dazu kommen eure eigenen, transparent im Dashboard einsehbaren API-Kosten." },
      { q: "Kann ich jederzeit kündigen?", a: "Ja, monatlich, keine Mindestlaufzeit, keine Kündigungsfrist über den laufenden Monat hinaus." },
      { q: "Woher weiß ich, dass eine gefundene E-Mail wirklich zu einer Person gehört?", a: "Frostbreaker filtert generische Adressen wie info@ oder office@ automatisch heraus. Nur E-Mails, die eindeutig einer Person zugeordnet sind, landen in eurer Leads-Liste." },
      { q: "Brauche ich eigene API-Keys? Ist das kompliziert?", a: "Einmal in den Einstellungen hinterlegt, läuft alles automatisch. In der kostenlosen Testphase führt euch die App Schritt für Schritt durch das Setup." },
      { q: "Wie unterscheidet sich das von Apollo/Hunter/Instantly?", a: "Die machen jeweils einen Teil des Workflows gut, mischen dabei aber meist personenbezogene und generische Adressen. Frostbreaker verbindet Suche, Anreicherung, Verifizierung und Personalisierung, filtert dabei automatisch auf echte Ansprechpartner, und bleibt auch nach dem Versand im Bild: Antworten lassen sich direkt in der App beantworten, das Dashboard zeigt gebuchte Meetings und Pipeline-Wert, nicht nur Öffnungsraten." },
      { q: "Wie schnell bin ich startklar?", a: "Ihr bucht ein 30-minütiges Gespräch, wir schauen uns gemeinsam an, wie ihr Frostbreaker für eure Ziele am effektivsten nutzt, und schalten danach euren Account frei. Ab dann: API-Keys eintragen, erste Suche starten, direkt in der App." },
      { q: "Woher kommen die Zahlen zum Skalierungspotenzial?", a: "Aus einer offen gelegten Beispielrechnung, nicht aus einer Zusicherung: Versandkapazität nach Instantly-Hypergrowth-Plan, Recherchezeit und Antwortquote nach branchenüblichen Annahmen. Die Rechnung samt Annahmen steht direkt neben den Zahlen." },
      { q: "Was passiert mit meinen Daten, wenn ich kündige?", a: "Eure Daten werden nach Vertragsende gelöscht oder auf Wunsch zurückgegeben, geregelt im AVV. Es gibt keine automatische Weiternutzung nach Kündigung." },
    ],
  },
  finalCta: {
    title: "Lasst uns eure Kaltakquise automatisieren.",
    body: "In einem 30-minütigen Gespräch schauen wir uns gemeinsam an, wie ihr Frostbreaker für eure Ziele und Bedürfnisse am effektivsten einsetzt. 14 Tage kostenlos, keine Kreditkarte nötig, danach monatlich kündbar.",
  },
  footer: {
    location: "Wien, Österreich",
    impressum: "Impressum",
    datenschutz: "Datenschutzerklärung",
    agb: "AGB",
    kontakt: "Kontakt",
  },
  contactPage: {
    eyebrow: "Kontakt",
    title: "Wer hinter Frostbreaker steckt",
    intro: "Kein Ticket-System, kein anonymes Support-Postfach. Wer bei Frostbreaker anfragt, spricht direkt mit mir.",
    name: "Youssef Tayachi",
    role: "Gründer & CEO, Frostbreaker",
    bio: "Ich wollte schon immer etwas Eigenes aufbauen, aber die größte Hürde war nie die Idee, sondern echte Kunden zu finden. Also habe ich Kaltakquise gemacht, von Hand: Listen zusammengesucht, Nummern angerufen, E-Mails einzeln getippt, oft ohne zu wissen, ob am anderen Ende überhaupt der richtige Ansprechpartner sitzt. Irgendwann war klar, wie viel Zeit und Geld dabei einfach verpufft, also habe ich angefangen, mir selbst Werkzeuge zu bauen, die diesen Prozess automatisieren. Daraus wurde Frostbreaker, seitdem geht mir nie mehr die Möglichkeit aus, die richtigen Menschen zu erreichen, und genau das will ich jetzt auch anderen Agenturen und Selbstständigen geben. Wenn du Fragen zum Produkt, zu Preisen oder zu eurem konkreten Use Case hast, meld dich einfach direkt.",
    emailLabel: "E-Mail",
    phoneLabel: "Telefon",
    calendlyLabel: "30 Minuten Call buchen",
    calendlyNote: "Kein Verkaufsgespräch von der Stange, sondern ein echtes Gespräch über eure Nische.",
    backLabel: "Zurück zur Startseite",
  },
  startPage: {
    title: "Lead-Gen und Cold Outreach für alle eure Kunden, aus einem Tool, unter eurem eigenen Namen.",
    body: "Ein eigener Workspace pro Kunde, ein teilbarer Report-Link im Look des jeweiligen Kunden, und ein Dashboard, das gebuchte Meetings und Pipeline-Wert zeigt, nicht nur Öffnungsraten.",
    ctaNote: "14 Tage kostenlos, keine Kreditkarte nötig. Monatlich kündbar.",
    workspaceHeading: "Ein Login, ein Workspace pro Kunde",
    factCard: { fact: "Bei reinen Versand-Tools ist Multi-Kunden-Verwaltung meist ein separat bepreistes Zusatzmodul.", sub: "Bei Frostbreaker ist das von Anfang an Teil des Produkts, weil Lead-Suche, Personalisierung und Reporting sowieso pro Kunde getrennt laufen müssen.", source: "Marktvergleich White-Label-Cold-Email-Tools, 2026" },
    finalHeading: "30 Minuten, wir zeigen es live an eurer eigenen Nische",
    finalBody: "Kein Verkaufsgespräch von der Stange, sondern eine echte Suche mit euren eigenen Kriterien.",
    backLink: "Lieber erst alle Details ansehen?",
  },
};

const en: typeof de = {
  nav: {
    produkt: "Product",
    produktItems: [
      { label: "Workflow", href: "#produkt" },
      { label: "Personalization", href: "#personalisierung" },
      { label: "Integrations", href: "#integrationen" },
    ],
    agenturen: "For Agencies",
    preise: "Pricing",
    vergleich: "Comparison",
    faq: "FAQ",
    kontakt: "Contact",
  },
  trustBar: {
    heading: "Runs on established services in the background",
    partners: ["OpenAI", "Google Places", "Hunter.io", "NeverBounce", "Instantly"],
  },
  heroIllustration: {
    badgeStat: "2×",
    badgeLabel: "more replies through real personalization",
    inboxLabel: "Replies, live from the dashboard",
    replies: [
      { name: "Markus Huber", company: "Huber Joinery", message: "Sounds great, tell me more!", status: "reply" },
      { name: "Julia Berger", company: "Berger Dental Practice", message: "Yes, happy to! Does Tuesday 2pm work?", status: "meeting" },
      { name: "Elena Roth", company: "Café Sonnenblick", message: "Interesting, when can we hop on a call?", status: "reply" },
    ],
    replyLabel: "Reply",
    meetingLabel: "Meeting booked",
  },
  calculator: {
    eyebrow: "Interactive",
    title: "Calculate your savings potential",
    subtitle: "How many qualified leads do you want to reach per month? We'll calculate live what that means for you.",
    sliderLabel: "Qualified leads / month",
    hoursUnit: "hrs",
    hoursLabel: "manual research saved / month",
    laborLabel: "labor cost equivalent for that",
    meetingsLabel: "meetings / month, calculated",
    planPrefix: "That fits the",
    apiCostPrefix: "approx.",
  },
  cta: {
    primary: "Start free trial",
    secondary: "Or book a call",
    trialNote: "14 days free, no credit card required. Cancel anytime, no contract.",
  },
  hero: {
    eyebrow: "Arguably the most direct AI use case for cold outreach",
    h1Pre: "Reach at least ",
    h1Accent: "5,000 real decision-makers",
    h1Post: " a week, fully automatically.",
    body: "Frostbreaker finds local businesses, identifies the right person behind them, verifies the email address and writes an individual icebreaker line, fully automatically. No info@, no office@: only real people you can actually reach.",
    factBadge: "Agencies get an average of $42 back for every dollar they spend on email.",
    factSource: "Source: Litmus, State of Email 2025",
    screenshotAlt: "Frostbreaker leads table with company logos, contact count and email status",
  },
  heroStats: [
    { value: "≈ 133 hrs", label: "manual research saved, per 1,000 leads" },
    { value: "€65", label: "actual API cost for that" },
    { value: "1 tool", label: "instead of four separate subscriptions" },
  ],
  leadSource: {
    eyebrow: "The lead source makes the difference",
    title: "Finds the small, local businesses that barely show up in classic lead databases",
    body1: "Classic B2B databases are built on LinkedIn profiles and structured company data, which favors businesses with a digital presence: software companies, larger mid-sized firms, agencies themselves. The trades business, the neighborhood restaurant, the dental practice, the small law firm, often exactly the businesses that need marketing the most because they've never invested in it in a structured way, barely show up there.",
    body2: "Frostbreaker instead searches directly via Google Places/Google Maps, where practically every business with a physical address is listed, regardless of digital maturity. For an agency, that means access to exactly the local clients that otherwise fall through the cracks of typical prospecting tools.",
  },
  localReachMockup: {
    typicalLabel: "Typical B2B database",
    frostbreakerLabel: "Frostbreaker, via Google Places",
    notListed: "not listed",
    businesses: [
      { name: "Kaiser Hair Salon", sub: "Single location salon" },
      { name: "Huber Joinery", sub: "Trades business, 6 employees" },
      { name: "Dr. Berger Dental", sub: "Solo practice" },
    ],
  },
  qualifiedLeads: {
    eyebrow: "Real people, not info@ addresses",
    title: "Every lead is a person you can actually reach",
    body1: "Most tools deliver whatever they find, including info@, office@ and contact@ addresses that nobody is specifically responsible for. Frostbreaker filters that out automatically: only addresses clearly assigned to a real person ever make it into your leads list.",
    body2: "No reply-to-nowhere. No answering into the void. Only real decision-makers.",
  },
  qualifiedMockup: {
    typicalLabel: "Typical tool",
    frostbreakerLabel: "Frostbreaker",
    genericNote: "role address, nobody specifically responsible",
    rows: [
      { generic: "info@huberjoinery.com", name: "Mark Huber", role: "Owner", email: "m.huber@huberjoinery.com" },
      { generic: "office@bergerdental.com", name: "Dr. Anna Berger", role: "Practice Owner", email: "a.berger@bergerdental.com" },
      { generic: "contact@kaisersalon.com", name: "Julia Kaiser", role: "Salon Manager", email: "j.kaiser@kaisersalon.com" },
    ],
  },
  painPoints: {
    title: "Sound familiar?",
    subtitle: "Every hour of manual research is an hour that's neither billed nor spent on new clients, and it multiplies with every additional client account.",
    items: [
      { title: "A separate tool chaos for every client", body: "One login for research, one for sending, one spreadsheet for reporting, starting over for every client. At month's end the report gets cobbled together by hand." },
      { title: "Hours sunk into research", body: "Google, LinkedIn, imprint search, guessing emails: before the first email for a client even goes out, half the day is already gone." },
      { title: "Four subscriptions for one workflow", body: "One tool for contacts, one for verification, one for personalization, one for sending, with CSV files exported by hand in between, for every client again." },
      { title: "Bounce rates that ruin the domain", body: "Unverified addresses kill deliverability. With several client domains at once, you often only notice once a client's reply rate suddenly collapses." },
      { title: "Generic emails everyone recognizes", body: "\"Hi {{Firstname}}, I saw that {{Company}}...\" with template-based personalization performs worse than none at all, and hurts client retention." },
      { title: "Info@ instead of a real contact", body: "Half of the \"found\" addresses land in a shared inbox nobody reads consistently. Cold email to info@ is barely better than no email at all." },
    ],
  },
  pillars: {
    eyebrow: "The effect in four sentences",
    title: "What actually changes for you",
    items: [
      { id: "money", title: "Save money", stat: "≈ €285", statLabel: "saved per month vs. a comparable 4-tool stack", body: "You only pay your actual API costs, ≈ €65 for 1,000 leads, plus the plan, no markups. A comparable stack of data source, sending tool and automation (e.g. Apollo/Clay + Instantly + Zapier) usually costs €250–650/month." },
      { id: "revenue", title: "Grow revenue", stat: "≈ 6", statLabel: "meetings/month, calculated at 1,000 emails sent", body: "Real personalization instead of templates, every email reaches a real person instead of a role address." },
      { id: "time", title: "Save time", stat: "≈ 133 hrs", statLabel: "manual research saved, per 1,000 leads", body: "No manual searching, no guessing addresses, no juggling CSVs between multiple tools." },
      { id: "risk", title: "Reduce risk", stat: "3-fold", statLabel: "verification, deliverability check and blocklist built in", body: "Protects sender reputation and domain before it becomes a problem, not after. EU hosting, encrypted credentials." },
    ],
  },
  workflow: {
    title: "One workflow. Four steps. Fully automatic, at the push of a button.",
    subtitle: "Set the niche and criteria once, Frostbreaker handles the rest: no manual step, no waiting on an intern, no hand-built spreadsheet.",
    steps: [
      { n: "1", title: "Search", body: "Enter a niche and location, Frostbreaker automatically finds matching businesses, for every client in their own workspace." },
      { n: "2", title: "Find", body: "Decision-makers with names are identified automatically, no info@ or office@ hits." },
      { n: "3", title: "Verify", body: "Every address is checked before it goes into a campaign. Frostbreaker also checks SPF, DKIM and DMARC on your sending domain before any campaign goes live." },
      { n: "4", title: "Personalize & Send", body: "An AI writes an individual icebreaker line per lead. Sequence, schedule and activation then run directly in Frostbreaker, no more switching tools." },
    ],
    fact: { fact: "Small, targeted lists get almost three times more replies than huge lists.", sub: "Better to write to a few well-chosen businesses than thousands at random.", source: "Woodpecker, citing Belkins' analysis of 16.5M emails, 2026" },
  },
  agency: {
    eyebrow: "For agencies",
    title: "Manage multiple clients without opening a new subscription for each one",
    body: "Running lead-gen or cold outreach for your own clients? Each client runs in its own, cleanly separated workspace, in that client's look, under a single login for your team.",
    features: [
      { id: "workspaces", title: "One login, one workspace per client", body: "Leads, campaigns and contacts run cleanly separated per client, without a separate subscription for each one. Workspaces can be created, renamed or removed in seconds." },
      { id: "branding", title: "Branding per client workspace", body: "Name, logo and accent color can be set per workspace, so what the client sees looks like the agency's own tool, not something foreign in the background." },
      { id: "reportLink", title: "Shareable report link, no login required for the client", body: "A link per workspace shows aggregated metrics in that client's look, without them needing their own account. Individual contact data is deliberately not shown to the client." },
    ],
    note: "With pure sending tools, multi-client management is usually a separately priced add-on, often with its own price per client workspace, on top of a tool that only handles sending. With Frostbreaker, that's part of the product from day one.",
  },
  agencyMockup: {
    workspacesLabel: "Workspaces",
    active: "active",
    workspaces: [
      { name: "Client: Acme Inc.", color: "#0EA5E9", active: true },
      { name: "Client: Example Co.", color: "#8B5CF6", active: false },
      { name: "Client: Northwind LLC", color: "#F59E0B", active: false },
    ],
    brandingLabel: "This workspace's branding",
    brandingValue: "Acme Inc. · Accent color #0EA5E9",
    reportLinkLabel: "Report link for the client",
    copyLabel: "Copy",
  },
  postSend: {
    eyebrow: "More than lead search",
    title: "Most tools stop once the email is sent. Frostbreaker doesn't.",
    body: "Through a connection to your sending tool, replies, bounces and meeting outcomes flow back into the same dashboard where the leads were found.",
    features: [
      { id: "replies", title: "Read replies and respond directly", body: "Every incoming reply lands in Frostbreaker with full text, AI classifies it instantly (interested, not interested, question). Reply directly from the app, no switching to a separate tool." },
      { id: "dashboard", title: "Revenue-focused dashboard, not just open rate", body: "Meetings booked, estimated pipeline value and cost per opportunity, right in the same dashboard as lead search." },
      { id: "status", title: "Lead status per contact, no separate CRM needed", body: "Contacted, replied, meeting booked, became a customer, all trackable directly in the leads table." },
      { id: "deliverability", title: "SPF, DKIM, DMARC: checked before you send", body: "Frostbreaker checks your sending domain live via DNS lookup and shows in plain language what to fix, no separate tool needed. Plus daily volume per mailbox at a glance, with a warning at risky send volumes." },
    ],
  },
  postSendMockup: {
    incomingLabel: "Incoming reply, automatically classified",
    exampleReply: "\"Sounds interesting, can we hop on a quick call next week?\"",
    statusInterested: "Interested",
    dashboardLabel: "Illustrative example dashboard",
    meetings: "Meetings booked",
    pipeline: "Pipeline value",
    bounce: "Bounce rate",
  },
  personalization: {
    eyebrow: "Personalization",
    title: "The AI agent isn't a black box",
    body: "Most tools spit out an icebreaker without you knowing what it's based on or how it sounds. With Frostbreaker, you configure it yourself: per niche, per campaign, as often as you like.",
    bullets: [
      { label: "Choose a data source:", body: "company description, website text, or both combined." },
      { label: "Fully editable system prompt:", body: "you set tone, rules and structure, no rigid template." },
      { label: "Define forbidden words:", body: "so no icebreaker sounds like generic AI." },
      { label: "Live-test on a real, researched company:", body: "before anything is saved or sent." },
    ],
    dataSourceLabel: "Data source",
    sourceOptions: ["Company description", "Website text", "Both combined"],
    promptLabel: "System prompt",
    promptLines: [
      "- Use only verifiable facts from the research.",
      "- No name, no greeting, no filler phrases.",
      "- Direct, concrete, like an observation before a sales question.",
    ],
    forbiddenLabel: "Forbidden words",
    forbiddenWords: ["respect", "admire", "proud", "praise", "thrilled"],
  },
  integrations: {
    eyebrow: "Fits into your stack",
    title: "Exports directly into the tools you already use",
    items: [
      { name: "Instantly", note: "Fully native campaign management, no CSV export needed" },
      { name: "Smartlead", note: "CSV import" },
      { name: "Lemlist", note: "CSV import" },
      { name: "HubSpot", note: "CSV import" },
      { name: "Pipedrive", note: "CSV import" },
      { name: "Salesforce", note: "CSV import" },
      { name: "Excel / Sheets", note: "Excel/CSV" },
      { name: "Zapier", note: "planned" },
    ],
  },
  usps: {
    eyebrow: "Why Frostbreaker",
    title: "Why Frostbreaker instead of four separate tools",
    items: [
      { title: "Everything in one tool, separated per client", body: "Search, enrichment, verification, personalization and export run in a single workflow, cleanly separated per client workspace. No more CSV back-and-forth between four subscriptions." },
      { title: "Individual AI summary per lead", body: "For every business, a fact-based summary is generated automatically, the basis for an icebreaker that genuinely sounds researched. Tone, rules and forbidden words are fully configurable.", fact: "Personal emails get roughly twice the reply rate of generic ones.", sub: "Almost nobody does this by hand because it takes too long. Frostbreaker does it for you, for every single email.", source: "Woodpecker, analysis of over 20M emails, 2026" },
      { title: "Built-in email verification", body: "Every found address is checked before it goes into a campaign. That protects your sender reputation, without an extra tool.", fact: "Verified email addresses land roughly twice as often as unverified ones.", sub: "Too many invalid addresses and your emails land in spam instead of the inbox.", source: "Industry benchmarks, email deliverability, 2026" },
      { title: "Bring your own key: full cost transparency", body: "You pay the actual API costs, no hidden markups. See live in the dashboard what a search actually cost." },
      { title: "Built with GDPR in mind", body: "EU hosting, encrypted credential storage, data minimization considered from the ground up." },
      { title: "Direct line to the team", body: "No ticket system. You talk directly to the people who built the tool, including real customizations on request." },
      { title: "Filters by real pain points, not just industry and location", body: "Google rating and whether a website even exists flow directly into the search. The icebreaker automatically factors this in, for example when a business hasn't had a recent review or has no website at all, instead of only knowing company name and industry." },
      { title: "Ready-made industry playbooks instead of your own trial and error", body: "Pre-built combinations of search criteria, pain-point filters and personalization hints for common niches, such as restaurants without a current website or trades businesses without online booking. One click instead of days of trial and error with search terms." },
    ],
  },
  trustBadges: [
    { id: "euHosting", title: "EU hosting", body: "Servers in Frankfurt, no data transfer outside the EU." },
    { id: "encryption", title: "Encrypted API keys", body: "Your credentials are stored encrypted, never in plain text." },
    { id: "byok", title: "BYOK cost control", body: "Full transparency over your actual API costs, live in the dashboard." },
  ],
  proofStat: {
    label: "Not a testimonial, a real number from our own account",
    body: "≈ 33 hours of manual research saved, roughly $1,600 in labor cost, at $2.75 in actual API costs.",
    sub: "That's what a single search looks like in our own dashboard: live, not calculated after the fact.",
  },
  scaling: {
    eyebrow: "Scaling potential",
    title: "What's mathematically possible if you go all-in",
    tiles: [
      { value: "125,000", label: "personalized emails sendable per month" },
      { value: "up to 125,000", label: "reachable businesses per month" },
      { value: "≈ 16,700 hrs", label: "manual research saved, roughly 100 full-time roles/month" },
      { value: "≈ 780", label: "qualified meetings per month, calculated" },
    ],
    methodologyLabel: "How these numbers come about, no guarantee:",
    methodologyBody: "We calculate with 125,000 emails sent per month (up to 500,000 would even be possible). Finding new businesses is practically unlimited, sending is the real bottleneck. For time savings we calculate roughly 8 minutes of manual work per contact, for cost savings a $50/hour wage. For meetings we calculate a 5% reply rate, a quarter of that positive, half of that leading to a meeting, industry-typical values, no guarantee. Nearly half of all replies actually come from the second email, not the first, which is why a clean export into your sending tool matters too. Your real results depend on your niche and your offer.",
    agencyOnlyNote: "These numbers show the potential with unlimited leads, available from the Agency plan. On Starter (up to 5,000 qualified leads/month) they scale down accordingly:",
    starterTiles: [
      { value: "≈ 133 hrs", label: "research time saved / month" },
      { value: "≈ $6,500", label: "labor cost equivalent for that" },
      { value: "≈ $220", label: "total cost (Frostbreaker + sending + APIs)" },
    ],
  },
  pricing: {
    eyebrow: "Pricing",
    title: "Fixed prices, visible immediately, quick intro call included",
    agencyBadge: "For agencies",
    note: "14 days free, no credit card required. Cancel anytime after, no minimum term. On top, only your own API costs, visible live in the dashboard.",
    plans: [
      {
        id: "starter",
        label: "Starter",
        price: "$99",
        priceNote: "/ month",
        features: [
          "1 workspace",
          "Up to 5,000 qualified leads/month",
          "Personal emails only, no info@",
          "Native Instantly campaigns",
          "Deliverability check & reply management",
        ],
        ctaLabel: "Start free trial",
        highlighted: false,
      },
      {
        id: "agency",
        label: "Agency",
        price: "from $199",
        priceNote: "/ month",
        features: [
          "Multiple workspaces, 1 per client",
          "Unlimited qualified leads",
          "Everything in Starter",
          "White-label reports with your branding",
          "Priority support",
        ],
        ctaLabel: "Discuss pricing",
        highlighted: true,
      },
    ],
  },
  comparison: {
    title: "Comparison",
    headerFrostbreaker: "Frostbreaker",
    headerOther: "Typical alternative stack for an agency",
    rows: [
      ["Finding local small businesses", "Yes, directly via Google Places/Maps", "Usually not listed, no LinkedIn profile or structured company data"],
      ["Everything in one workflow", "Yes", "No, separate research tool + sending tool + own reporting"],
      ["Managing multiple clients", "Own workspace per client included", "Usually a separately priced white-label add-on"],
      ["Client-facing reporting", "Shareable report link in the client's look", "Manually assembled from multiple tools"],
      ["AI personalization per lead", "Yes, with configurable rules", "Partial, often a separate tool needed"],
      ["Built-in email verification", "Yes", "Separate tool needed"],
      ["EU hosting", "Yes", "Varies, mostly US providers"],
      ["Only real decision-makers, no info@", "Automatically filtered", "Usually unfiltered"],
      ["Price transparency", "Fixed prices, 14 days free trial", "Usually a custom quote, no trial"],
      ["Support", "Direct line to the founder", "Ticket system"],
    ] as [string, string, string][],
  },
  trust: {
    title: "Privacy isn't a checkbox, it's part of the architecture",
    links: { datenschutz: "Privacy Policy", agb: "Terms", avv: "DPA" },
  },
  why: {
    title: "Why Frostbreaker exists",
    body: "Outbound teams today usually combine four to five separate tools to get from the first search term to a personalized, verified email. Frostbreaker reduces this workflow to a single tool, with full cost transparency instead of flat-rate subscriptions and no CSV back-and-forth between providers.",
    earlyAccess: { title: "Early access instead of a big customer list", body: "Frostbreaker is currently in active testing with the first partner agencies. Deliberately a small, closely supported group instead of an anonymous mass product, every adjustment goes straight into the next sprint." },
    founderLabel: "From the founder",
    founderQuote: "\"I always wanted to build something of my own. The hardest part was never the idea, it was finding clients: cold calls and emails by hand, hours of research, never knowing if any of it would land. So I built the tool I wish I'd had, and I've never run out of real decision-makers to reach since.\"",
    founderName: "Youssef Tayachi",
    founderRole: "Founder & CEO, Frostbreaker",
    poweredBy: { title: "Runs on established services", body: "No black box, just well-known, vetted providers in the background." },
  },
  faq: {
    title: "Frequently asked questions",
    items: [
      { q: "Is this GDPR-compliant?", a: "The app itself is built with privacy in mind (EU hosting, encryption, data minimization). How you contact the found leads is still subject to the direct-marketing rules that apply to you. We're happy to advise you on your specific situation in a call." },
      { q: "Can I use this as an agency for multiple clients at once?", a: "Yes, there are separate workspaces per client, including their own name, logo and accent color. Each workspace can share a report link that shows your client aggregated metrics in their own look, without them needing their own account." },
      { q: "What does it cost?", a: "$99/month for the Starter plan (1 workspace, up to 5,000 qualified leads), 14 days free, cancel anytime after. The Agency plan (multiple workspaces, unlimited) starts from $199/month, tailored to your number of client workspaces, so let's have a quick chat about that. On top come your own API costs, transparently visible in the dashboard." },
      { q: "Can I cancel anytime?", a: "Yes, monthly, no minimum term, no notice period beyond the current month." },
      { q: "How do I know a found email really belongs to a person?", a: "Frostbreaker automatically filters out generic addresses like info@ or office@. Only emails clearly assigned to a person make it into your leads list." },
      { q: "Do I need my own API keys? Is that complicated?", a: "Once entered in settings, everything runs automatically. During the free trial, the app walks you through setup step by step." },
      { q: "How is this different from Apollo/Hunter/Instantly?", a: "They each do part of the workflow well, but usually mix personal and generic addresses. Frostbreaker connects search, enrichment, verification and personalization, automatically filtering for real decision-makers, and stays in the loop after sending too: replies can be answered directly in the app, and the dashboard shows booked meetings and pipeline value, not just open rates." },
      { q: "How fast can I get started?", a: "You book a 30-minute call, we look together at how to get the most out of Frostbreaker for your goals, and unlock your account afterwards. From there: add your API keys, start your first search, directly in the app." },
      { q: "Where do the scaling potential numbers come from?", a: "From an openly disclosed example calculation, not a promise: sending capacity based on the Instantly Hypergrowth plan, research time and reply rate based on industry-typical assumptions. The calculation and its assumptions are shown right next to the numbers." },
      { q: "What happens to my data if I cancel?", a: "Your data is deleted after the contract ends, or returned on request, as governed by the DPA. There's no automatic continued use after cancellation." },
    ],
  },
  finalCta: {
    title: "Let's automate your cold outreach.",
    body: "In a 30-minute call, we'll look together at how to get the most out of Frostbreaker for your specific goals and needs. 14 days free, no credit card required, cancel anytime after that.",
  },
  footer: {
    location: "Vienna, Austria",
    impressum: "Legal notice",
    datenschutz: "Privacy policy",
    agb: "Terms",
    kontakt: "Contact",
  },
  contactPage: {
    eyebrow: "Contact",
    title: "Who's behind Frostbreaker",
    intro: "No ticket system, no anonymous support inbox. If you reach out to Frostbreaker, you talk to me directly.",
    name: "Youssef Tayachi",
    role: "Founder & CEO, Frostbreaker",
    bio: "I always wanted to build something of my own, but the biggest hurdle was never the idea, it was finding real clients. So I did cold outreach by hand: building lists, dialing numbers, typing out emails one by one, often without even knowing if the right person was on the other end. At some point it was obvious how much time and money that was quietly burning, so I started building my own tools to automate the process. That became Frostbreaker, and I've never run out of ways to reach the right people since, and that's exactly what I want to give other agencies and freelancers too. If you have questions about the product, pricing, or your specific use case, just reach out.",
    emailLabel: "Email",
    phoneLabel: "Phone",
    calendlyLabel: "Book a 30-minute call",
    calendlyNote: "No off-the-shelf sales pitch, just a real conversation about your niche.",
    backLabel: "Back to homepage",
  },
  startPage: {
    title: "Lead-gen and cold outreach for all your clients, from one tool, under your own name.",
    body: "A dedicated workspace per client, a shareable report link in that client's look, and a dashboard that shows booked meetings and pipeline value, not just open rates.",
    ctaNote: "14 days free, no credit card required. Cancel anytime.",
    workspaceHeading: "One login, one workspace per client",
    factCard: { fact: "With pure sending tools, multi-client management is usually a separately priced add-on.", sub: "With Frostbreaker it's part of the product from day one, because lead search, personalization and reporting have to run separately per client anyway.", source: "Market comparison, white-label cold email tools, 2026" },
    finalHeading: "30 minutes, we'll show it live for your own niche",
    finalBody: "No off-the-shelf sales pitch, just a real search with your own criteria.",
    backLink: "Prefer to see all the details first?",
  },
};

export type Dictionary = typeof de;
export const dict: Record<Lang, Dictionary> = { de, en };
